### ISSUE TITLE
Var2Compform/PromoteSubentries.ini should be renamed

### ISSUE THREAD

**Issue by WesPeacock** [sil-dictionary-lexical-services/SubentryPromotion#15]
Originally the se2lx.ini sections were part of this file. They were removed, so this file now is only an ini file for Var2Compform.pl. It should probably be renamed to Var2Compform.ini.

Here's a list of things to change 
>$ grep -Rno PromoteSubentries.ini *
SampleFiles/setup-sepromo-complex.sh:10:PromoteSubentries.ini
SampleFiles/setup-sepromo-simple.sh:10:PromoteSubentries.ini
Var2Compform/runVar2Compform.sh:26:PromoteSubentries.ini
Var2Compform/runVar2Compform.sh:27:PromoteSubentries.ini
Var2Compform/runVar2Compform.sh:33:PromoteSubentries.ini
Var2Compform/Subentry_Handling_Notes_files/Sample_INI_File.html:59:PromoteSubentries.ini
Var2Compform/Var2Compform.pl:18:PromoteSubentries.ini
Var2Compform/Var2Compform.pl:19:PromoteSubentries.ini

**Comment by bbryson** [comment]
I agree.  Can we go ahead and do this one?
