### ISSUE TITLE
handling of homograph numbers

### ISSUE THREAD

**Issue by bbryson** [sil-dictionary-lexical-services/SubentryPromotion#19]
The promote script needs to be aware of homograph numbers on subentries.

There are many ways that subentries can be specified, but the recommended way is to glue the number right onto the vernacular form in the \se field (or whatever the subentry marker is).  At least this approach needs to be interpreted correctly.

If there are other ways to specify homographs, it's okay if it can handle those also, but at least the way that the FLEx import understands needs to be handled.

If an entry has:

\lx black
\de a dark color
\se blackberry1
\de a small composite fruit

then when the subentry gets promoted, it would come out as:

\lx blackberry
\hm 1
\mn black
\de a small composite fruit

**Comment by WesPeacock** [comment]
I think the easiest way to handle this is just an extra pass through the data:
> for my $oplline (@opledfile_in) {
     $oplline =~ s/(\\($subentrymkrsregex)\ [^#]*?)([0-9]+#)/$1#\\hm $3/g;
      }

**Comment by WesPeacock** [comment]
Actually better to put it in the promotion part of the script, as subentries are not supposed to have \hm fields
